backend/backend/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include('newsapp.urls')),
    path('todo/', include('todoapp.urls')),
    path('menu/', include('restaurant_menu.urls')),
    path('multi/', include('multirelationexample.urls')),
]

backend/multirelationexample/urls.py
from django.urls import path
from . import views
app_name = 'multiplerelationexample'

urlpatterns = [
    path('create/meal/', views.CreateMeal.as_view()),
]

backend/newsapp/urls.py
from django.urls import path
from . import views

app_name = 'newsapp'

urlpatterns = [
        path('articles/', views.NewsArticleList.as_view()),
        path('article/<int:pk>', views.NewsArticleDetail.as_view()),
]

backend/restaurant_menu/urls.py
from django.urls import path

from . import views

app_name = "restaurant_menu"

urlpatterns = [
    path('items/', views.ItemList.as_view()),
    path('items/<int:pk>', views.ItemDetail.as_view()),
]

backend/todoapp/urls.py
from django.urls import path
from . import views

app_name='todoapp'

urlpatterns = [
    path('tasks/', views.TaskList.as_view()),
    path('task/<int:pk>', views.TaskDetail.as_view()),
    path('do/<int:pk>', views.markDone),
    path('undo/<int:pk>', views.markUndone),
]

backend/multirelationexample/models.py
from django.db import models

class Meal(models.Model):
    name = models.CharField(max_length=50)
    date = models.DateField()
    members = models.ManyToManyField(to="Member", related_name="meals")

class Member(models.Model):
    name  = models.CharField(max_length=50)
    age = models.PositiveIntegerField()
    address = models.TextField()

    def __str__(self, *args, **kwargs):
        return self.name

backend/newsapp/models.py
from django.db import models

class NewsArticle(models.Model):
    title = models.CharField(max_length=150)
    author = models.CharField(max_length=20)
    published = models.DateTimeField()
    content = models.TextField()
    imageUrl = models.URLField()

backend/restaurant_menu/models.py
from django.db import models

class Item(models.Model):

    name = models.CharField(max_length=50)
    description = models.TextField()
    price = models.PositiveIntegerField()
    rating = models.DecimalField(max_digits=3, decimal_places=2)


class  ItemImage(models.Model):

    url = models.URLField()
    item = models.ForeignKey(Item, related_name="images", on_delete=models.CASCADE)

backend/todoapp/models.py
from django.db import models

priority_choices = [ (1,"High"),
                     (2,"Medium"),
                     (3,"Low") ]

class Todo(models.Model):
    name = models.CharField(max_length=120)
    description = models.TextField()
    isComplete = models.BooleanField(default=False)
    priority = models.IntegerField(choices=priority_choices)

backend/multirelationexample/forms.py
from django import forms
from . import models

class CreateMealForm(forms.ModelForm):

    class Meta :
        model = models.Meal
        fields = '__all__'
    
    date = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'])
    
    members = forms.ModelMultipleChoiceField(
        queryset = models.Member.objects.all(),
        widget = forms.CheckboxSelectMultiple
    )

backend/restaurant_menu/forms.py
from django import forms

backend/multirelationexample/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from django.urls import reverse_lazy

from . import models
from . import forms

class CreateMeal(CreateView):
    model = models.Meal
    form_class = forms.CreateMealForm
    template_name = "createmealform.html"
    #success_url = reverse_lazy('main')

backend/newsapp/views.py
from rest_framework import generics
from . import models
from . import serializers

class NewsArticleList(generics.ListCreateAPIView):
    queryset = models.NewsArticle.objects.all()
    serializer_class = serializers.NewsArticleSerializer

class NewsArticleDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = models.NewsArticle.objects.all()
    serializer_class = serializers.NewsArticleSerializer

backend/restaurant_menu/views.py
from rest_framework import generics

from . import models
from . import serializers

class ItemList(generics.ListCreateAPIView):
    queryset = models.Item.objects.all()
    serializer_class = serializers.GetItemSerializer

class ItemDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = models.Item.objects.all()
    serializer_class = serializers.GetItemSerializer

backend/todoapp/views.py
from rest_framework import generics
from . import models
from . import serializers
import json
from rest_framework.response import Response
from django.http import JsonResponse


class TaskList(generics.ListCreateAPIView):
    queryset = models.Todo.objects.all()
    serializer_class = serializers.TodoTaskSerializer

class TaskDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = models.Todo.objects.all()
    serializer_class = serializers.TodoTaskSerializer

def markDone(request, pk):
    d = None
    try:
        m = models.Todo.objects.all().filter(pk=pk)[0]
        m.isComplete = True
        m.save()
        d = {"message":"success"}
    except :
        d = {"message":"failed to change state"}
    return JsonResponse(d)

def markUndone(request, pk):
    d = None
    try:
        m = models.Todo.objects.all().filter(pk=pk)[0]
        m.isComplete = False
        m.save()
        d = {"message":"success"}
    except :
        d = {"message":"failed to change state"}
    return JsonResponse(d)

backend/multirelationexample/templates/createmealform.html
{% extends 'multi_base.html' %}
{% load bootstrap3 %}

{% block content %}

  <style>
    .form-main {
      padding : 5%;
      margin-top : 5%;
      margin-bottom : 5%;
      border-radius : 10px;
      background : #e6e6e6;
    }

  </style>

  <div class="form-main">
    <div class = "container">
      <h1 class="mt-2">Create Meal</h1>
      <hr class="mt-0 mb-4">

      <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" name="" value="Create" class="btn btn-primary">
      </form>
    </div>
  </div>

  <script>
  $(function () {
    $("#id_date").datetimepicker({
      format: 'd/m/Y H:i',
    });
  });
  
</script>


{% endblock %}

backend/multirelationexample/templates/multi_base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.js" integrity="sha512-WNLxfP/8cVYL9sj8Jnp6et0BkubLP31jhTG9vhL/F5uEZmg5wEzKoXp1kJslzPQWwPT1eyMiSxlKCgzHLOTOTQ==" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>

    <style>
      .container-main {
        width : 80vw;
        margin : auto;
      }
    </style>

    <title>Multi Relation Forms Example</title>

  </head>
  <body>
    <div class="container-main">
      <div class="row justify-content-center">
        <div class="col-10">
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>